/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Address } from './models/address';
export type { CustomerRequest } from './models/customer-request';
export type { CustomerResponse } from './models/customer-response';
