/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  categoryId?: number;
  description?: string;
  id?: string;
  name?: string;
  price?: number;
}
