/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InventoryResponse } from '../../models/inventory-response';
import { OrderRequest } from '../../models/order-request';

export interface CheckAvailabilityExchange$Params {
      body: OrderRequest
}

export function checkAvailabilityExchange(http: HttpClient, rootUrl: string, params: CheckAvailabilityExchange$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InventoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, checkAvailabilityExchange.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InventoryResponse>>;
    })
  );
}

checkAvailabilityExchange.PATH = '/api/order/check-availability-exchange';
