/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceInstance } from '../../models/service-instance';

export interface GetServiceInstances$Params {
  applicationName: string;
}

export function getServiceInstances(http: HttpClient, rootUrl: string, params: GetServiceInstances$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceInstance>>> {
  const rb = new RequestBuilder(rootUrl, getServiceInstances.PATH, 'get');
  if (params) {
    rb.path('applicationName', params.applicationName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ServiceInstance>>;
    })
  );
}

getServiceInstances.PATH = '/api/order/service-instances/{applicationName}';
