/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetAllProducts$Params as GetAllProducts$Params } from './fn/product-controller/get-all-products';
export { getAllProducts as getAllProducts } from './fn/product-controller/get-all-products';
export type { CreateProduct$Params as CreateProduct$Params } from './fn/product-controller/create-product';
export { createProduct as createProduct } from './fn/product-controller/create-product';
export type { GetById$Params as GetById$Params } from './fn/product-controller/get-by-id';
export { getById as getById } from './fn/product-controller/get-by-id';
export type { GetAllCategories$Params as GetAllCategories$Params } from './fn/product-controller/get-all-categories';
export { getAllCategories as getAllCategories } from './fn/product-controller/get-all-categories';
