/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderLineItemDto {
  id?: number;
  price: number;
  productId: string;
  quantity: number;
  skuCode: string;
}
