/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderLineItemDto } from '../models/order-line-item-dto';
export interface OrderRequest {
  customerId: string;
  id?: number;
  items: Array<OrderLineItemDto>;
  paymentMethod: 'PAYPAL' | 'CREDIT_CARD' | 'VISA' | 'MASTERCARD' | 'BITCOIN' | 'SAMSUNG';
  reference?: string;
  totalAmount: number;
}
