/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceInstance {
  host?: string;
  instanceId?: string;
  metadata?: {
[key: string]: string;
};
  port?: number;
  scheme?: string;
  secure?: boolean;
  serviceId?: string;
  uri?: string;
}
