/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface CustomerRequest {
  address?: Address;
  email: string;
  firstName: string;
  id?: string;
  lastName: string;
}
