/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { checkAvailability } from '../fn/order-controller/check-availability';
import { CheckAvailability$Params } from '../fn/order-controller/check-availability';
import { checkAvailabilityExchange } from '../fn/order-controller/check-availability-exchange';
import { CheckAvailabilityExchange$Params } from '../fn/order-controller/check-availability-exchange';
import { checkAvailabilityRest } from '../fn/order-controller/check-availability-rest';
import { CheckAvailabilityRest$Params } from '../fn/order-controller/check-availability-rest';
import { createOrder } from '../fn/order-controller/create-order';
import { CreateOrder$Params } from '../fn/order-controller/create-order';
import { getAllOrders } from '../fn/order-controller/get-all-orders';
import { GetAllOrders$Params } from '../fn/order-controller/get-all-orders';
import { getOrder } from '../fn/order-controller/get-order';
import { GetOrder$Params } from '../fn/order-controller/get-order';
import { getServiceInstances } from '../fn/order-controller/get-service-instances';
import { GetServiceInstances$Params } from '../fn/order-controller/get-service-instances';
import { InventoryResponse } from '../models/inventory-response';
import { OrderResponse } from '../models/order-response';
import { placeOrder } from '../fn/order-controller/place-order';
import { PlaceOrder$Params } from '../fn/order-controller/place-order';
import { sendTestEvent } from '../fn/order-controller/send-test-event';
import { SendTestEvent$Params } from '../fn/order-controller/send-test-event';
import { ServiceInstance } from '../models/service-instance';

@Injectable({ providedIn: 'root' })
export class OrderControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllOrders()` */
  static readonly GetAllOrdersPath = '/api/order';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders$Response(params?: GetAllOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderResponse>>> {
    const obs = getAllOrders(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders(params?: GetAllOrders$Params, context?: HttpContext): Observable<Array<OrderResponse>> {
    const resp = this.getAllOrders$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<OrderResponse>>): Array<OrderResponse> => r.body)
    );
  }

  /** Path part for operation `createOrder()` */
  static readonly CreateOrderPath = '/api/order';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder$Response(params: CreateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = createOrder(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder(params: CreateOrder$Params, context?: HttpContext): Observable<number> {
    const resp = this.createOrder$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `sendTestEvent()` */
  static readonly SendTestEventPath = '/api/order/send-test-event';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendTestEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendTestEvent$Response(params?: SendTestEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = sendTestEvent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendTestEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendTestEvent(params?: SendTestEvent$Params, context?: HttpContext): Observable<void> {
    const resp = this.sendTestEvent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `checkAvailability()` */
  static readonly CheckAvailabilityPath = '/api/order/check-availability';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkAvailability()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkAvailability$Response(params: CheckAvailability$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InventoryResponse>>> {
    const obs = checkAvailability(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkAvailability$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkAvailability(params: CheckAvailability$Params, context?: HttpContext): Observable<Array<InventoryResponse>> {
    const resp = this.checkAvailability$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<InventoryResponse>>): Array<InventoryResponse> => r.body)
    );
  }

  /** Path part for operation `checkAvailabilityRest()` */
  static readonly CheckAvailabilityRestPath = '/api/order/check-availability-rest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkAvailabilityRest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkAvailabilityRest$Response(params: CheckAvailabilityRest$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InventoryResponse>>> {
    const obs = checkAvailabilityRest(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkAvailabilityRest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkAvailabilityRest(params: CheckAvailabilityRest$Params, context?: HttpContext): Observable<Array<InventoryResponse>> {
    const resp = this.checkAvailabilityRest$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<InventoryResponse>>): Array<InventoryResponse> => r.body)
    );
  }

  /** Path part for operation `checkAvailabilityExchange()` */
  static readonly CheckAvailabilityExchangePath = '/api/order/check-availability-exchange';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkAvailabilityExchange()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkAvailabilityExchange$Response(params: CheckAvailabilityExchange$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InventoryResponse>>> {
    const obs = checkAvailabilityExchange(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkAvailabilityExchange$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  checkAvailabilityExchange(params: CheckAvailabilityExchange$Params, context?: HttpContext): Observable<Array<InventoryResponse>> {
    const resp = this.checkAvailabilityExchange$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<InventoryResponse>>): Array<InventoryResponse> => r.body)
    );
  }

  /** Path part for operation `placeOrder()` */
  static readonly PlaceOrderPath = '/api/order/async';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `placeOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  placeOrder$Response(params: PlaceOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    const obs = placeOrder(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `placeOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  placeOrder(params: PlaceOrder$Params, context?: HttpContext): Observable<{
}> {
    const resp = this.placeOrder$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getOrder()` */
  static readonly GetOrderPath = '/api/order/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrder$Response(params: GetOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderResponse>> {
    const obs = getOrder(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrder(params: GetOrder$Params, context?: HttpContext): Observable<OrderResponse> {
    const resp = this.getOrder$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<OrderResponse>): OrderResponse => r.body)
    );
  }

  /** Path part for operation `getServiceInstances()` */
  static readonly GetServiceInstancesPath = '/api/order/service-instances/{applicationName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getServiceInstances()` instead.
   *
   * This method doesn't expect any request body.
   */
  getServiceInstances$Response(params: GetServiceInstances$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceInstance>>> {
    const obs = getServiceInstances(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getServiceInstances$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getServiceInstances(params: GetServiceInstances$Params, context?: HttpContext): Observable<Array<ServiceInstance>> {
    const resp = this.getServiceInstances$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ServiceInstance>>): Array<ServiceInstance> => r.body)
    );
  }

}
